### ISSUE TITLE
Maintenance issue 

### ISSUE THREAD

**Issue by jamesarems** [project-fifo/cerberus#6]
Hi team,

Recently i heard about this project and tried it in my office lab . smartos is good and working fantastic. But im facing some problem with FIFO zone. I have installed fifo zone as described in the documentation. Installation works fine but 3 service is going maintenance mode every time. I cant able to access fifo web management. 

STATE          STIME    FMRI
online          9:21:18 svc:/pkgsrc/epmd:default
maintenance    11:19:45 svc:/network/snarl:default
maintenance    11:21:14 svc:/network/sniffle:default
maintenance    11:21:33 svc:/network/howl:default

I am using ibm x3650 server. and also using latest fifo-project 0.8 .

**Comment by killfill** [comment]
Hi James!

It would be very helpfull if you can share some data for example from the logs of each service, maybe they describe an error there that can be resolves.

There is a mailing list (project-fifo@googlegroups.com) there are more people that can be more helpfull too!

**Comment by Licenser** [comment]
Oh I didn't even see this, @jamesarems this is probably not the ideel place to ask :) we don't look here too often for issues, mostly we have https://jira.project-fifo.net for that. I hope your issue is resolved if not you probably do have a non aVX compatible CPU . The release branch is optimized as it is intended for production use so we take each advantage we can get, however if you use the dev branch the AVX requirement is disabled there.

**Comment by jamesarems** [comment]
@Licenser Thanks for your reply.
https://docs.project-fifo.net/docs/building-non-avx-packages . This documentation helps me .  Thanks .
